# Generated by Django 4.0.1 on 2022-01-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
    ]
